### ISSUE TITLE
API change of redux-saga in the beta channel

### ISSUE THREAD

**Issue by saplf** [infinitered/reactotron-redux-saga#2]
As https://github.com/redux-saga/redux-saga/pull/1555#issue-207490800 mentioned, the API `asEffect` in `redux-saga/utils` package had been removed since their `1.0.0-beta3` pre-release:

> API changes in this PR:
> 
> - API `asEffect` is removed
> - API `is.effect` is added to test whether an object is an effect
> - `effectTypes` is exported by `redux-saga/effects`.
>
> ...
> Effects inspection utils in this PR are relatively simple and straightforward. Documentation for effects should be updated and tells users **that `Effect` is an object that consists of a `type`, a `payload` and an internal symbol `IO`**. So users could import `is` and `effectTypes` to test whether an effect is of a specific type like in [checkers](https://github.com/redux-saga/redux-saga/pull/1555/files#diff-5d397e302f1805e01eb7aeb798443633).

So, these codes need an update:
https://github.com/infinitered/reactotron-redux-saga/blob/d1b17e9d31a57155283688f02cb8bd246f9ccb34/src/get-effect-description.js#L3

https://github.com/infinitered/reactotron-redux-saga/blob/d1b17e9d31a57155283688f02cb8bd246f9ccb34/src/get-effect-name.js#L1

**Comment by rmevans9** [comment]
Thanks for reporting this. I will be getting back into this libraries code here soon so I will look into this.

**Comment by rmevans9** [comment]
This has been resolved.
